name: Continuous Integration

on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    uses: ./.github/workflows/reusable-install-dependencies.yml
    with:
      task: lint
      name: eslint

  test:
    uses: ./.github/workflows/reusable-install-dependencies.yml
    with:
      task: test
      name: vitest
