name: Continuous Integration

on:
  pull_request:
    branches: ['develop']
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4

      - name: Reuse setup action
        uses: ./.github/actions/setup

      - name: Test with eslint
        run: yarn lint

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4

      - name: Reuse setup action
        uses: ./.github/actions/setup

      - name: Test with vitest
        run: yarn test
