name: Continuous Integration

on:
  push:
    branches: ['feature/PW-249-cicd']
  pull_request:
    branches: ['develop']

jobs:
  lint:
    uses: ./.github/workflows/reusable-install-dependencies.yml
    with:
      task: lint
      name: eslint

  test:
    uses: ./.github/workflows/reusable-install-dependencies.yml
    with:
      task: test
      name: vitest
